// Supply-side "supply graph" — PROSPECT merchants the agent has discovered but
// not yet onboarded (distinct from lib/data.ts EXPERIENCES, which are live).
// Simulated; in production this is assembled nightly from Google Business,
// Yelp, Instagram/TikTok, menu PDFs, OpenTable/Resy, sites, and Reddit.

export type Stage =
  | "Discovered"
  | "Qualified"
  | "Proposal sent"
  | "Replied"
  | "Call booked"
  | "Onboarded";

export const STAGES: Stage[] = [
  "Discovered",
  "Qualified",
  "Proposal sent",
  "Replied",
  "Call booked",
  "Onboarded",
];

export interface Prospect {
  id: string;
  name: string;
  category: string;
  neighborhood: string;
  lat: number;
  lng: number;
  rating: number;
  reviewCount: number;
  reviewVelocity: number; // reviews / month — demand signal
  priceLevel: 1 | 2 | 3 | 4;
  offPeakWindow: string; // human-readable slow window
  offPeakUtilizationPct: number; // est. % full during that window
  signals: string[]; // the substantive, personalizable details
  sources: string[]; // where the supply graph traversed
  lastRefresh: string;
  // economics inputs
  avgTicket: number; // $ per cover at full price
  grossMarginPct: number; // merchant gross margin
  dailyCapacity: number; // covers/slots per day
  // owner contact (fake)
  contact: { owner: string; email: string; phone: string };
  stage: Stage;
  fitNote: string; // one-line vertical-fit summary
}

export const PROSPECTS: Prospect[] = [
  {
    id: "the-lark",
    name: "Olio e Limone",
    category: "Italian restaurant",
    neighborhood: "Downtown",
    lat: 34.4188,
    lng: -119.7005,
    rating: 4.6,
    reviewCount: 1840,
    reviewVelocity: 22,
    priceLevel: 3,
    offPeakWindow: "Tue–Thu, 4–6pm",
    offPeakUtilizationPct: 38,
    signals: [
      "Reviews repeatedly praise the Negroni and the burrata",
      "Happy hour runs Tue–Thu 4–6pm but is under-promoted",
      "Tuesday dinner covers run ~38% of capacity",
    ],
    sources: ["Google Business", "Yelp", "Instagram", "Menu PDF"],
    lastRefresh: "2h ago",
    avgTicket: 58,
    grossMarginPct: 68,
    dailyCapacity: 120,
    contact: { owner: "Marco R.", email: "marco@olioelimone.example", phone: "+1 805 555 0142" },
    stage: "Qualified",
    fitNote: "High-margin Italian with a clear, under-marketed off-peak window.",
  },
  {
    id: "third-window",
    name: "Third Window Brewing",
    category: "Brewery & taproom",
    neighborhood: "The Funk Zone",
    lat: 34.4139,
    lng: -119.69,
    rating: 4.5,
    reviewCount: 920,
    reviewVelocity: 14,
    priceLevel: 2,
    offPeakWindow: "Mon–Wed afternoons",
    offPeakUtilizationPct: 31,
    signals: [
      "Patio empty most weekday afternoons per recent photos",
      "Strong group/event reviews — bachelor parties, work outings",
      "No current happy-hour or group offer listed anywhere",
    ],
    sources: ["Google Business", "Instagram", "Reddit r/santabarbara", "Site"],
    lastRefresh: "5h ago",
    avgTicket: 32,
    grossMarginPct: 74,
    dailyCapacity: 160,
    contact: { owner: "Dana W.", email: "dana@thirdwindow.example", phone: "+1 805 555 0173" },
    stage: "Discovered",
    fitNote: "Group-friendly taproom, very high margin, zero existing offers.",
  },
  {
    id: "satellite",
    name: "Satellite Wine Bar",
    category: "Natural wine bar",
    neighborhood: "Downtown",
    lat: 34.4201,
    lng: -119.7035,
    rating: 4.7,
    reviewCount: 610,
    reviewVelocity: 18,
    priceLevel: 3,
    offPeakWindow: "Tue–Wed evenings",
    offPeakUtilizationPct: 42,
    signals: [
      "Reviews love the by-the-glass flights and the cheese board",
      "Midweek is quiet; weekends sell out",
      "Active, aesthetic Instagram with engaged local following",
    ],
    sources: ["Google Business", "Yelp", "Instagram", "Resy"],
    lastRefresh: "1h ago",
    avgTicket: 46,
    grossMarginPct: 70,
    dailyCapacity: 70,
    contact: { owner: "Elise T.", email: "elise@satellitewine.example", phone: "+1 805 555 0119" },
    stage: "Discovered",
    fitNote: "Tastemaker wine bar; flights are a natural bundle.",
  },
  {
    id: "ca-yoga",
    name: "Coastal Flow Yoga",
    category: "Yoga studio",
    neighborhood: "The Mesa",
    lat: 34.4018,
    lng: -119.719,
    rating: 4.8,
    reviewCount: 430,
    reviewVelocity: 12,
    priceLevel: 2,
    offPeakWindow: "Midday weekday classes",
    offPeakUtilizationPct: 28,
    signals: [
      "Midday classes run nearly empty; evenings are full",
      "Strong first-timer reviews — good intro-class candidate",
      "Drop-in price is high vs. competitors (intro offer opportunity)",
    ],
    sources: ["Google Business", "Instagram", "Site", "Mindbody"],
    lastRefresh: "3h ago",
    avgTicket: 26,
    grossMarginPct: 82,
    dailyCapacity: 60,
    contact: { owner: "Priya S.", email: "priya@coastalflow.example", phone: "+1 805 555 0188" },
    stage: "Qualified",
    fitNote: "Very high margin; empty midday slots ideal for sampler classes.",
  },
  {
    id: "mesa-taqueria",
    name: "La Super-Rica Adjacent",
    category: "Taquería",
    neighborhood: "The Mesa",
    lat: 34.4025,
    lng: -119.7182,
    rating: 4.4,
    reviewCount: 2200,
    reviewVelocity: 30,
    priceLevel: 1,
    offPeakWindow: "Weekday 2–5pm",
    offPeakUtilizationPct: 35,
    signals: [
      "Cult following for the al pastor; lines on weekends only",
      "Cash-heavy, no online ordering, no marketing presence",
      "Afternoons dead between lunch and dinner rushes",
    ],
    sources: ["Google Business", "Yelp", "Reddit r/santabarbara"],
    lastRefresh: "6h ago",
    avgTicket: 18,
    grossMarginPct: 60,
    dailyCapacity: 220,
    contact: { owner: "Eddie M.", email: "eddie@superrica-adj.example", phone: "+1 805 555 0155" },
    stage: "Discovered",
    fitNote: "High-velocity favorite with no digital footprint — pure upside.",
  },
  {
    id: "riviera-tours",
    name: "Riviera E-Bike Tours",
    category: "Tour operator",
    neighborhood: "The Riviera",
    lat: 34.4402,
    lng: -119.701,
    rating: 4.9,
    reviewCount: 280,
    reviewVelocity: 9,
    priceLevel: 3,
    offPeakWindow: "Weekday mornings",
    offPeakUtilizationPct: 22,
    signals: [
      "Tiny but flawless reviews — sunset tour is the standout",
      "Weekday morning departures rarely fill",
      "Perfect for the 'bring three friends' group mechanic",
    ],
    sources: ["Google Business", "TripAdvisor", "Instagram"],
    lastRefresh: "4h ago",
    avgTicket: 75,
    grossMarginPct: 65,
    dailyCapacity: 24,
    contact: { owner: "Kai L.", email: "kai@rivierebike.example", phone: "+1 805 555 0166" },
    stage: "Proposal sent",
    fitNote: "Experiential, group-shaped, big empty weekday-morning inventory.",
  },
  {
    id: "funk-coffee",
    name: "Lighthouse Roasters",
    category: "Specialty coffee",
    neighborhood: "The Funk Zone",
    lat: 34.4132,
    lng: -119.6908,
    rating: 4.6,
    reviewCount: 740,
    reviewVelocity: 16,
    priceLevel: 2,
    offPeakWindow: "Weekday 1–4pm lull",
    offPeakUtilizationPct: 33,
    signals: [
      "Morning rush is packed; afternoons are sleepy",
      "Roasts on-site; reviews mention the cupping flights",
      "Could host a paid cupping/tasting in the dead afternoon window",
    ],
    sources: ["Google Business", "Instagram", "Site"],
    lastRefresh: "2h ago",
    avgTicket: 14,
    grossMarginPct: 78,
    dailyCapacity: 200,
    contact: { owner: "Tomas B.", email: "tomas@lighthouse.example", phone: "+1 805 555 0101" },
    stage: "Replied",
    fitNote: "On-site roastery; afternoon cupping is a clean experience SKU.",
  },
  {
    id: "harbor-kayak",
    name: "Harbor Sea-Cave Kayak Co.",
    category: "Watersports",
    neighborhood: "SB Harbor",
    lat: 34.4035,
    lng: -119.6907,
    rating: 4.8,
    reviewCount: 510,
    reviewVelocity: 11,
    priceLevel: 2,
    offPeakWindow: "Weekday late mornings",
    offPeakUtilizationPct: 26,
    signals: [
      "Sunrise tours sell out; mid-morning weekday tours don't",
      "Reviews highlight the guides and sea-lion sightings",
      "Already group-oriented (tandem kayaks)",
    ],
    sources: ["Google Business", "TripAdvisor", "FareHarbor"],
    lastRefresh: "7h ago",
    avgTicket: 65,
    grossMarginPct: 62,
    dailyCapacity: 40,
    contact: { owner: "Brodie K.", email: "brodie@harborkayak.example", phone: "+1 805 555 0177" },
    stage: "Discovered",
    fitNote: "Group inventory with predictable weekday-morning gaps.",
  },
  {
    id: "eastside-clay",
    name: "Eastside Clay Studio",
    category: "Pottery studio",
    neighborhood: "Eastside",
    lat: 34.4255,
    lng: -119.6845,
    rating: 4.9,
    reviewCount: 190,
    reviewVelocity: 7,
    priceLevel: 2,
    offPeakWindow: "Weeknight early slots",
    offPeakUtilizationPct: 30,
    signals: [
      "Date-night wheel classes are the hero; weekends book out",
      "Early weeknight slots go unsold",
      "Ships finished pieces — strong post-experience hook",
    ],
    sources: ["Google Business", "Instagram", "Site"],
    lastRefresh: "9h ago",
    avgTicket: 58,
    grossMarginPct: 72,
    dailyCapacity: 24,
    contact: { owner: "June H.", email: "june@eastsideclay.example", phone: "+1 805 555 0133" },
    stage: "Qualified",
    fitNote: "Beloved class with empty early-week slots; great group SKU.",
  },
  {
    id: "mesa-cocktail",
    name: "The Good Lion",
    category: "Craft cocktail bar",
    neighborhood: "Downtown",
    lat: 34.4185,
    lng: -119.7008,
    rating: 4.7,
    reviewCount: 1120,
    reviewVelocity: 20,
    priceLevel: 3,
    offPeakWindow: "Sun–Tue evenings",
    offPeakUtilizationPct: 40,
    signals: [
      "Famous for seasonal, fresh-pressed cocktails",
      "Early-week evenings noticeably slower",
      "Bartenders are a draw — a 'cocktail lab' would sell",
    ],
    sources: ["Google Business", "Yelp", "Instagram"],
    lastRefresh: "3h ago",
    avgTicket: 42,
    grossMarginPct: 76,
    dailyCapacity: 90,
    contact: { owner: "Sloane D.", email: "sloane@thegoodlion.example", phone: "+1 805 555 0144" },
    stage: "Discovered",
    fitNote: "Marquee cocktail bar; slow early-week nights to fill.",
  },
  {
    id: "goleta-farm",
    name: "Ellwood Canyon Farm",
    category: "Farm experience",
    neighborhood: "Goleta",
    lat: 34.4631,
    lng: -119.8276,
    rating: 4.8,
    reviewCount: 150,
    reviewVelocity: 5,
    priceLevel: 2,
    offPeakWindow: "Weekday mornings",
    offPeakUtilizationPct: 20,
    signals: [
      "Family farm breakfasts get glowing but sparse reviews",
      "Almost no online discoverability",
      "Weekday mornings wide open",
    ],
    sources: ["Google Business", "Facebook", "Site"],
    lastRefresh: "11h ago",
    avgTicket: 44,
    grossMarginPct: 64,
    dailyCapacity: 40,
    contact: { owner: "Hank & Rosa", email: "hello@ellwoodfarm.example", phone: "+1 805 555 0190" },
    stage: "Discovered",
    fitNote: "Under-discovered family experience with huge weekday capacity.",
  },
  {
    id: "downtown-jazz",
    name: "SOhO Music Club",
    category: "Live music venue",
    neighborhood: "Downtown",
    lat: 34.4192,
    lng: -119.6995,
    rating: 4.5,
    reviewCount: 880,
    reviewVelocity: 13,
    priceLevel: 2,
    offPeakWindow: "Early sets / weeknights",
    offPeakUtilizationPct: 36,
    signals: [
      "Headliner nights pack out; early sets are thin",
      "Small-plates kitchen is underused",
      "Natural fit for a 'rooftop jazz + small plates' bundle",
    ],
    sources: ["Google Business", "Instagram", "Site", "Eventbrite"],
    lastRefresh: "5h ago",
    avgTicket: 38,
    grossMarginPct: 66,
    dailyCapacity: 120,
    contact: { owner: "Marcus V.", email: "marcus@sohosb.example", phone: "+1 805 555 0122" },
    stage: "Discovered",
    fitNote: "Venue + kitchen combo; early sets are easy inventory to fill.",
  },
  {
    id: "lather-salon",
    name: "Lather & Co. Salon",
    category: "Hair salon & spa",
    neighborhood: "The Mesa",
    lat: 34.402,
    lng: -119.7188,
    rating: 4.7,
    reviewCount: 380,
    reviewVelocity: 14,
    priceLevel: 3,
    offPeakWindow: "Tue–Thu midday",
    offPeakUtilizationPct: 30,
    signals: [
      "Reviews rave about the balayage and the head-spa add-on",
      "Midday weekday chairs sit empty; evenings & weekends are booked solid",
      "Got burned by a Groupon-facial-style deal years ago — wary of discounts",
    ],
    sources: ["Google Business", "Yelp", "Instagram", "Mindbody"],
    lastRefresh: "2h ago",
    avgTicket: 85,
    grossMarginPct: 78,
    dailyCapacity: 40,
    contact: { owner: "Renata K.", email: "renata@latherco.example", phone: "+1 805 555 0211" },
    stage: "Qualified",
    fitNote: "High-LTV beauty: empty midday chairs, clients rebook monthly.",
  },
  {
    id: "haven-rooftop",
    name: "Haven Rooftop Lounge",
    category: "Rooftop lounge & bottle service",
    neighborhood: "Downtown",
    lat: 34.4196,
    lng: -119.6998,
    rating: 4.3,
    reviewCount: 540,
    reviewVelocity: 19,
    priceLevel: 4,
    offPeakWindow: "Sun–Wed nights",
    offPeakUtilizationPct: 35,
    signals: [
      "Weekends sell out; Sun–Wed tables go mostly empty",
      "Table/bottle service is the model — a public discount would cheapen the door",
      "Heavy Instagram presence; bachelorette + birthday demand",
    ],
    sources: ["Google Business", "Instagram", "Resy"],
    lastRefresh: "4h ago",
    avgTicket: 220,
    grossMarginPct: 80,
    dailyCapacity: 18,
    contact: { owner: "Andre P.", email: "andre@havenrooftop.example", phone: "+1 805 555 0224" },
    stage: "Discovered",
    fitNote: "High-margin status inventory — access play, never a discount.",
  },
  {
    id: "montecito-golf",
    name: "Montecito Twilight Golf",
    category: "Golf course",
    neighborhood: "Montecito",
    lat: 34.4368,
    lng: -119.632,
    rating: 4.5,
    reviewCount: 410,
    reviewVelocity: 8,
    priceLevel: 3,
    offPeakWindow: "Weekday twilight (after 3pm)",
    offPeakUtilizationPct: 28,
    signals: [
      "Weekday twilight tee sheet is wide open",
      "Foursomes book together — the group of four is built into the format",
      "Strong cart + F&B attach after the round",
    ],
    sources: ["Google Business", "GolfNow", "Site"],
    lastRefresh: "8h ago",
    avgTicket: 95,
    grossMarginPct: 65,
    dailyCapacity: 72,
    contact: { owner: "Bill T.", email: "bill@montecitogolf.example", phone: "+1 805 555 0233" },
    stage: "Qualified",
    fitNote: "Twilight inventory + a built-in foursome = the group mechanic for free.",
  },
  {
    id: "plunge-sb",
    name: "Plunge SB — Sauna & Cold",
    category: "Sauna & cold plunge recovery",
    neighborhood: "The Funk Zone",
    lat: 34.4135,
    lng: -119.6905,
    rating: 4.8,
    reviewCount: 210,
    reviewVelocity: 16,
    priceLevel: 2,
    offPeakWindow: "Weekday mornings & early afternoons",
    offPeakUtilizationPct: 26,
    signals: [
      "Sauna + cold-plunge contrast is the hero; group sessions trend on Instagram",
      "Mornings and early afternoons run quiet; evenings fill",
      "No intro offer or membership funnel in place yet",
    ],
    sources: ["Google Business", "Instagram", "Site"],
    lastRefresh: "3h ago",
    avgTicket: 45,
    grossMarginPct: 80,
    dailyCapacity: 50,
    contact: { owner: "Sage M.", email: "sage@plungesb.example", phone: "+1 805 555 0247" },
    stage: "Discovered",
    fitNote: "Trendy, high-margin recovery; intro → membership funnel wide open.",
  },
  {
    id: "alley-axe",
    name: "Alley & Axe",
    category: "Bowling & axe throwing",
    neighborhood: "Goleta",
    lat: 34.4435,
    lng: -119.827,
    rating: 4.4,
    reviewCount: 660,
    reviewVelocity: 17,
    priceLevel: 2,
    offPeakWindow: "Weekday daytime",
    offPeakUtilizationPct: 30,
    signals: [
      "Lanes and axe bays sit empty weekday daytime",
      "Birthday and corporate-group reviews everywhere",
      "Sold by the lane/bay — already a group purchase",
    ],
    sources: ["Google Business", "Yelp", "Instagram"],
    lastRefresh: "5h ago",
    avgTicket: 30,
    grossMarginPct: 70,
    dailyCapacity: 100,
    contact: { owner: "Drew H.", email: "drew@alleyandaxe.example", phone: "+1 805 555 0259" },
    stage: "Discovered",
    fitNote: "Group-native social inventory; the unit IS the group.",
  },
  {
    id: "plaza-buffet",
    name: "Plaza Buffet",
    category: "Buffet restaurant",
    neighborhood: "Goleta",
    lat: 34.4421,
    lng: -119.829,
    rating: 3.6,
    reviewCount: 540,
    reviewVelocity: 6,
    priceLevel: 1,
    offPeakWindow: "Weekday afternoons",
    offPeakUtilizationPct: 30,
    signals: [
      "Large capacity, frequently half-empty",
      "Mixed reviews — inconsistent service is a recurring complaint",
      "Owner eager to discount aggressively to drive any volume",
    ],
    sources: ["Google Business", "Yelp"],
    lastRefresh: "12h ago",
    avgTicket: 24,
    grossMarginPct: 52,
    dailyCapacity: 250,
    contact: { owner: "Sal D.", email: "sal@plazabuffet.example", phone: "+1 805 555 0262" },
    stage: "Discovered",
    fitNote: "Lots of empty capacity, but quality risk — a value-score test case.",
  },
];

export function getProspect(id: string): Prospect | undefined {
  return PROSPECTS.find((p) => p.id === id);
}

// Supply-graph headline stats (the letter's "real-time graph at marginal cost").
export const SUPPLY_STATS = {
  tracked: 142,
  citiesActive: 1,
  sources: 6,
  refreshedNightly: true,
};
